name: compare_s3_replaces

on:
  workflow_dispatch:
    manual: false
  schedule:
    - cron: '*/10 * * * *'

jobs:
  replace:
    name: Replace NYC taxi tripdata
    runs-on: ubuntu-latest
    env:
      CH_TB_TOKEN: ${{ secrets.CH_TB_TOKEN }}
      GCS_TB_TOKEN: ${{ secrets.GCS_TB_TOKEN }}
      S3_TB_TOKEN: ${{ secrets.S3_TB_TOKEN }}
      GCS_HC_TB_TOKEN: ${{ secrets.GCS_HC_TB_TOKEN }}
      TB_HOST: ${{ secrets.TB_HOST }}
    steps:
    - name: Set YELLOW_TRIPDATA_URL
      run: echo "YELLOW_TRIPDATA_URL=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_$(shuf -i 2009-2019 -n 1)-0$(shuf -i 1-9 -n 1).parquet" >> $GITHUB_ENV
    - name: CH replace
      run: |
        curl \
          -H "Authorization: Bearer ${CH_TB_TOKEN}" \
          -X POST "https://${TB_HOST}.tinybird.co/v0/datasources" \
          -d "format=parquet" \
          -d "name=nyc_taxis" \
          -d "mode=replace" \
          --data-urlencode "url=${YELLOW_TRIPDATA_URL}"
    - name: GCS replace
      run: |
        curl \
          -H "Authorization: Bearer ${GCS_TB_TOKEN}" \
          -X POST "https://${TB_HOST}.tinybird.co/v0/datasources" \
          -d "format=parquet" \
          -d "name=nyc_taxis" \
          -d "mode=replace" \
          --data-urlencode "url=${YELLOW_TRIPDATA_URL}"
    - name: GCS HC replace
      run: |
        curl \
          -H "Authorization: Bearer ${GCS_HC_TB_TOKEN}" \
          -X POST "https://${TB_HOST}.tinybird.co/v0/datasources" \
          -d "format=parquet" \
          -d "name=nyc_taxis" \
          -d "mode=replace" \
          --data-urlencode "url=${YELLOW_TRIPDATA_URL}"
    - name: s3 replace
      run: |
        curl \
          -H "Authorization: Bearer ${S3_TB_TOKEN}" \
          -X POST "https://${TB_HOST}.tinybird.co/v0/datasources" \
          -d "format=parquet" \
          -d "name=nyc_taxis" \
          -d "mode=replace" \
          --data-urlencode "url=${YELLOW_TRIPDATA_URL}"