name: gcs_replaces_metrics

on:
  schedule:
    - cron: '* */2 * * *'

jobs:
  replace:
    name: Trigger Export Endpoint
    runs-on: ubuntu-latest
    steps:
    - name: cURL request
      run: |
        curl \
          -H "Authorization: Bearer ${GCS_TB_TOKEN}" \
          -X POST "https://${TB_HOST}.tinybird.co/v0/datasources" \
          -d "format=parquet" \
          -d "name=nyc_taxis" \
          -d "mode=replace" \
          --data-urlencode "url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_$(shuf -i 2009-2019 -n 1)-0$(shuf -i 1-9 -n 1).parquet"
      env:
        GCS_TB_TOKEN: ${{ secrets.GCS_TB_TOKEN }}
        TB_HOST: ${{ secrets.TB_HOST }}
